[tool.poetry]
name = "test1"
version = "0.1.0"
description = ""
authors = ["William Jamir Silva <williamjamir@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
[tool.poetry.dependencies.aiocache]
git = "https://github.com/aio-libs/aiocache.git"
rev = "ae5948b2d99dcaa68fe02fd3086a3351a867c85b"
extras = [
    "redis",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
