[tool.poetry]
name = "test1"
version = "0.1.0"
description = ""
authors = ["William Jamir Silva <williamjamir@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mypy = "^1.5.1"
httpx = "^0.27.0"
pytest = "^8.1.1"
prefect = "2.16.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
