name: Check

on:
  workflow_call:
    
jobs:

  setup:
    uses: ./.github/workflows/setup.yml
  linters:
    needs: [setup]
    uses: ./.github/workflows/linters.yml
  tests:
    needs: [setup]
    uses: ./.github/workflows/tests.yml
  some-check:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Run something
        run: |
          echo "my test" 
  
  final_message:
    needs: [linters]
    if: github.event_name == 'push' && failure()
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: | 
          echo "Execute with failure"
          echo ${{ job.status }}