name: Check

on:
  workflow_call:
    
jobs:

  setup:
    uses: ./.github/workflows/setup.yml
  some-check:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        id: cache-venv
        with:
          path: |
              ~/.local
              ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements**.txt', 'poetry.lock') }}
          
      - name: Install poetry
        if: ${{ hashFiles('poetry.lock') != '' }} && steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1.3.4
        with: 
          virtualenvs-create: false
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
          
      - run: poetry install
      - run: poetry run pytest 
  
