name: Check

on:
  workflow_call:
    
jobs:

  setup:
    uses: ./.github/workflows/setup.yml
  some-check:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest 
  
