name: My Check

on:
  push:

jobs:
  
  check: 
    runs-on: ubuntu-latest
    steps: 

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get deploy environments
        id: deployEnv
        run: |
          deploy_environments=[]
          is_develop_branch=$([[ "${{ github.ref }}" == refs/heads/develop ]] && echo true || echo false)
          is_production_branch=$([[ "${{ github.ref }}" == refs/heads/production ]] && echo true || echo false)
          is_production_synced_with_develop=$(git cherry origin/production origin/develop)

          echo "Is develop: ${is_develop_branch}"
          echo "Is prod: ${is_production_branch}"
          echo "Is synced: ${is_production_synced_with_develop}"
          
          deploy_environments=""
          if [[ $is_develop == true ]]; then
            deploy_environments="staging"
          elif [[ $is_prod == true ]] && [[ -n $changes ]]; then
            deploy_environments="${{ inputs.production_environments }}"
          elif [[ $is_prod == true ]] && [[ -z $changes ]]; then
            echo "::error::Cannot deploy out of sync production branch to production environments: ${{ inputs.production_environments }}"
          fi
          echo "deploy_environments=[${deploy_environments}]" >> $GITHUB_OUTPUT
          echo "${deploy_environments}"
            
