name: Update requirements

on:
  push:
   #- cron: '0 9 * * 5'  #  every friday at 9 a.m.



jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      postgres:
        image: postgres:16.0-alpine
        
        
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install renovate
        
