name: Update requirements

on:
  pull_request:  # TODO(william) remove this line when PR is ready  
  push:
   #- cron: '0 9 * * 5'  #  every friday at 9 a.m.



jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      postgres:
        image: postgres:12.16-alpine
        
        
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install renovate

      - name: Trigger renovate manually (in order to evalute cc-tool packges)
        run: npx renovate --token ${{ secrets.RENOVATE_TOKEN }} williamjamir/test1 --log-file renovate.log --log-file-level DEBUG
      - name: test
        run: cat renovate.log
        
