name: Check

on:
  workflow_call:
    
jobs:

  ssome-linters:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Run LINTER
        run: |
            echo "::error file=MYFILE,line=10,endLine=10,title=TITLE::MESSAGE"
      - name: Hi
        run: | 
          echo "Execute with failure"
          echo ${{ job.status }}
